### ISSUE TITLE
Remove Payment.js

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/svelte-credit-card#7]

**Comment by thiagozanetti** [comment]
Is there any specific reason or just a design decision?

**Comment by CharlyJazz** [comment]
### Design Decision, check this:

https://github.com/CharlyJazz/svelte-credit-card/blob/master/rollup.config.js#L3

We need put this plugin because payment.js have a very old module export implementation, in addition, payment.js brings a lot of functionality that this project does not use. We could reduce the final bundle of the package if we only create a helper with the regex / validations of each credit card

### I put this code but is soooo uselesss, because we just need validate de credit card number prop

https://github.com/CharlyJazz/svelte-credit-card/blob/master/src/CreditCard.svelte#L143


### Check this interesting resource about validation 

https://www.youtube.com/watch?v=opSvzBlUMZA
